### ISSUE TITLE
'class std::function<void(void*, IEvent*)>' has no member named 'target_type'

### ISSUE THREAD

**Issue by LinArcX** [PreciousRoy0/SDL-RPG-Game-Tutorial-Series#1]
Hi. and thank you for your great working. I'm on linux and try to compile and run your samples via cmake. specifically, i want to compile your: __17-TextBox_Checkbox_Panel_Button__ sampel. when i run make command, i get some errors:
```
╰ make
Scanning dependencies of target rpg
[  3%] Building CXX object CMakeFiles/rpg.dir/lib/Color.cpp.o
In file included from /mnt/D/WorkSpace/C++/SDL-RPG-Game/test_uit/lib/Color.cpp:1:
/mnt/D/WorkSpace/C++/SDL-RPG-Game/test_uit/lib/Color.h: In function 'bool operator==(const Color&, const Color&)':
/mnt/D/WorkSpace/C++/SDL-RPG-Game/test_uit/lib/Color.h:16:63: warning: self-comparison always evaluates to false [-Wtautological-compare]
   16 |             if (a.A != b.A || a.B != b.B || a.G != b.G || a.R != a.R)
      |                                                           ~~~ ^~ ~~~
[  6%] Building CXX object CMakeFiles/rpg.dir/lib/EventListener.cpp.o
In file included from /mnt/D/WorkSpace/C++/SDL-RPG-Game/test_uit/lib/EventListener.h:2,
                 from /mnt/D/WorkSpace/C++/SDL-RPG-Game/test_uit/lib/EventListener.cpp:1:
/mnt/D/WorkSpace/C++/SDL-RPG-Game/test_uit/lib/IEvent.h:6:2: error: expected ';' after class definition
    6 | }
      |  ^
      |  ;
/mnt/D/WorkSpace/C++/SDL-RPG-Game/test_uit/lib/EventListener.cpp: In member function 'void EventListener::RemoveListener(std::function<void(void*, IEvent*)>)':
/mnt/D/WorkSpace/C++/SDL-RPG-Game/test_uit/lib/EventListener.cpp:25:28: error: '__gnu_cxx::__alloc_traits<std::allocator<std::function<void(void*, IEvent*)> >, std::function<void(void*, IEvent*)> >::value_type' {aka 'class std::function<void(void*, IEvent*)>'} has no member named 'target_type'
   25 |         if (m_Functions[i].target_type() == func.target_type())
      |                            ^~~~~~~~~~~
/mnt/D/WorkSpace/C++/SDL-RPG-Game/test_uit/lib/EventListener.cpp:25:50: error: 'class std::function<void(void*, IEvent*)>' has no member named 'target_type'
   25 |         if (m_Functions[i].target_type() == func.target_type())
      |                                                  ^~~~~~~~~~~
make[2]: *** [CMakeFiles/rpg.dir/build.make:76: CMakeFiles/rpg.dir/lib/EventListener.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/rpg.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by PreciousRoy0** [comment]
Hello,

as far as i know it should just work. bet lets have a loot at what is wrong. what version of c++ are you using.

I just downloaded the files off of github and it compiles just fine for me, so i am thinking it is probably a configuration issue. let me know what you think.

Edit: I was just looking at the error at line 6 "virtual ~IEvent() = 0 {}" it might be that your compiler does not support virtual destructors. try removing the "virtual" and "= 0 {}" and see if that helps anything.  fixing this will probably fix the other errors as wel seeing they are also related to "IEvent"

**Comment by LinArcX** [comment]
Actually i'm using: `gcc (GCC) 9.1.0`.
Yes, seems gcc doesn't support virtual destructors. So i comment it out and tried again. but also failed again.
Finally i comment lines 28-32 of file: `EventListener.cpp` and it works properly. Also i created a repo that add some stuffs to your project (like cmakelists.txt, ..) that make it suitiable to build and run on linux machines:
https://github.com/LinArcX/SDL-RPG-Game

Edit: this is the CMakeLists.txt of this sample:
https://github.com/LinArcX/SDL-RPG-Game/blob/master/17-TextBox_Checkbox_Panel_Button/CMakeLists.txt

**Comment by PreciousRoy0** [comment]
cool thanks for sharing :}

I have actually started making new vids and will soon be posting them on youtube.
also i stream 3 days a week so your welcome to join.

**Comment by LinArcX** [comment]
Sure, I appreciate your working. Keep going :)
