### ISSUE TITLE
cannot dynamic_cast 'ev' (of type 'class IEvent*') to type 'class MouseUpEvent*' (source type is not polymorphic)  

### ISSUE THREAD

**Issue by LinArcX** [PreciousRoy0/SDL-RPG-Game-Tutorial-Series#2]
Hi again. i'm playing around with your samples. and in sample: __14-ui_event_poller__
, on line 48 of main file:
```
void OnMousUpEvent(IEvent* ev)
    {
        MouseUpEvent* mev = dynamic_cast<MouseUpEvent*>(ev);
        spr2loc.X = mev->x;
        spr2loc.Y = mev->y;
    }
```
I'v got these errors:

```
[ 16%] Building CXX object CMakeFiles/rpg.dir/lib/SDL_GameStateManager.cpp.o
[ 22%] Building CXX object CMakeFiles/rpg.dir/src/main.cpp.o
/mnt/D/WorkSpace/C++/SDL-RPG-Game/14-ui_event_poller/src/main.cpp: In member function 'void TestState::OnMousUpEvent(IEvent*)':
/mnt/D/WorkSpace/C++/SDL-RPG-Game/14-ui_event_poller/src/main.cpp:48:59: error: cannot dynamic_cast 'ev' (of type 'class IEvent*') to type 'class MouseUpEvent*' (source type is not polymorphic)
   48 |         MouseUpEvent* mev = dynamic_cast<MouseUpEvent*>(ev);
      |                                                           ^
make[2]: *** [CMakeFiles/rpg.dir/build.make:271: CMakeFiles/rpg.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/rpg.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

Compiler: gcc 9.1.0
Os: void linux

**Comment by PreciousRoy0** [comment]
hello,

I think it might be the issue related to the virtual destructor.
you removed "virtual ~IEvent() = 0 {}" and so no virtual elements are override. so i think the compiler does nothing with IEvent try creating a virtual function like  "virtual Implement() = 0 ;" and override it in MouseUpEvent i think that might fix your problem.

**Comment by LinArcX** [comment]
Yeah, it compiles perfectly but nothing happend. I mean __OnMousUpEvent()__ never called.

**Comment by PreciousRoy0** [comment]
hey,

um try pressing the space, if i remember correctly and if you watch the videos you will see that i probably changed the code to test something so it does not get hit on mouse up see code

`		if (state.IsKeyDown(Keys::SPACE))
		{
			MouseUpEvent* ev = new MouseUpEvent;
			ev->x = mState.Location.X;
			ev->y = mState.Location.Y;
			spr2list.SetEvent(ev);
		}`

it forces the sprite to follow the mouse

**Comment by LinArcX** [comment]
Yes. Now it works like a charm. :)
